export { Contact } from "./contact"
export { Blog } from "./blog"
export { ChooseUs } from "./choose-us"
export { Reviews } from "./reviews"
export { Buildings } from "./buildings"
export { Hero } from "./hero"
export { BuildingsInner } from "./buildings-inner"
